port: "8080"
logging_interval: 1  # minutes
log_directory: "funding_logs"

exchanges:
  binance:
    enabled: true
    base_url: "https://fapi.binance.com"
    api_key: ""
    api_secret: ""
    
  bybit:
    enabled: true
    base_url: "https://api.bybit.com"
    api_key: ""
    api_secret: ""
    
  okx:
    enabled: false
    base_url: "https://www.okx.com"
    api_key: ""
    api_secret: ""
    
  mexc:
    enabled: true
    base_url: "https://contract.mexc.com"
    api_key: ""
    api_secret: ""
    
  bitget:
    enabled: true
    base_url: "https://api.bitget.com"
    api_key: ""
    api_secret: ""
    
  gate:
    enabled: true
    base_url: "https://api.gateio.ws"
    api_key: ""
    api_secret: ""
    
  deribit:
    enabled: true
    base_url: "https://www.deribit.com"
    api_key: ""
    api_secret: ""
    
  xt:
    enabled: false
    base_url: "https://api.xt.com"
    api_key: ""
    api_secret: ""
    
  kucoin:
    enabled: true
    base_url: "https://api-futures.kucoin.com"
    api_key: ""
    api_secret: "" 