port: "8080"

exchanges:
  binance:
    enabled: true
    base_url: "https://fapi.binance.com"
    api_key: ""
    api_secret: ""
    
  bybit:
    enabled: true
    base_url: "https://api.bybit.com"
    api_key: ""
    api_secret: ""
    
  okx:
    enabled: false
    base_url: "https://www.okx.com"
    api_key: ""
    api_secret: "" 